on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - run: |
          python --version
          poetry env info

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'poetry'

      - run: |
          python --version
          poetry env info

      - run: |
          poetry install

      - run: |
          poetry env info

      - run: |
          poetry run python --version

  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - run: |
          python --version
          poetry env info

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'poetry'

      - run: |
          python --version
          poetry env info

      - run: |
          poetry install

      - run: |
          poetry env info

      - run: |
          poetry run python --version
